config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout

  end

  resources :statuses

  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get "/:id", to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
	# attr_accessible :content, :user_id 

	belongs_to :user

	validates :content, presence: true,
						length: { minimum: 2 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  	has_many :statuses

  # 	validates :first_name, presence: true 
  #   validates :last_name, presence: true 
  #   validates :profile_name, presence: true
  # #                          ,format: {
  #                           with: /\A[a-zA-Z\-\_]+\Z/,
  #                           message: "must be formatted correctly."
  # }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  if 
  	@user = User.find_by_profile_name(params[:id])
  	@statuses = @user.statuses.all
  	render action: :show
  else
  	render file: 'public/404', status: 404, formats: [:html]  		
  	end

  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create]


  # GET /statuses
  # GET /statuses.json
  def index
    
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
   @statuses = Status.all
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create

    @status = Status.new(status_params)


    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ultrabook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <nav class="top-bar" data-topbar>
  <div class="row">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "UltraBook", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
 <section class="top-bar-section">
        <ul class="left">
          <li><%= link_to "All Statuses", feed_path %></li>
        </ul>

    <ul class="nav pull-right">
      <% if user_signed_in? %>
    <li><%= link_to current_user.id, edit_user_registration_path %></li>
    <li><%= link_to "Log Out", logout_path %></li>
    <% else %>
    <li><%= link_to "Register", register_path %></li>
    <li><%= link_to "Login", login_path %></li>
    <% end %>
     </ul>
  </section>
</div>

</nav>
</div>
</div>
<div class="container">
<% if flash[:notice] %>
  <div class="alert alert-success">
  <button class="close" data-dismiss="alert">x</button>
  <%= flash[:notice] %>
  </div>
  <% end %>
  <div class="container">
<% if flash[:alert] %>
  <div class="alert alert-warning">
  <button class="close" data-dismiss="alert">x</button>
  <%= flash[:alert] %>
  </div>
  <% end %>





<%= yield %>





<script src="/app/assets/javascripts/jquery.js"></script>
  <script src="/app/assets/javascripts/foundation.min.js"></script>
  <script>
    $(document).foundation();
  </script>

</body>
</html>

app/views/profiles/show.html.erb
<h1> Meu Profile</h1>
	<p><%= @user_id %></p>

<% if @statuses %>
	<% @statuses.each do |status| %>

	<div class="panel">
	<%= status.content %><br>
	<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
	</div>

	<% end %>

	<% else %>
	<%= root_path %>
	<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

       <!-- havia colocado :user_id pra que? -->
    <%= f.input :user_id, collection: User.all, 
                          label_method: :id %>
    <%= f.input :content %>
  <br>
  <div class="actions">
    <%= f.button :submit, class: "radius" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
    <h1>All of the Statuses</h1>
</div>



<%= link_to "Create new", new_status_path, class:["button success radius"] %>

<div class="background">
<% @statuses.each do |status| %>
  <div class="status">
    <strong>Name:</strong>
    <%= status.user_id %>
    <p><%= status.content %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + " ago ",status %>
    <span class="admin">|
    <%= link_to "Edit", edit_status_path(status) %> |
    <%= link_to "Destroy", status, method: :delete, data: { confirm: "Are you Sure? "} %>
    </span>
  </div>
  </div>
<% end %>
</div>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
 	<%= @status.user_id %>
 	<%= @status.user.first_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>